### ISSUE TITLE
About package versions

### ISSUE THREAD

**Issue by YangJae96** [dipamgoswami/ADC#1]
Hi. Thank you for great work!

Which version of pytorch did you use?

Could you upload some requirements.txt file to download the pacakages that is used in this work?!

Thanks in advance.

**Comment by dipamgoswami** [comment]
Hi, I have updated the readme file with the dependencies.

**Comment by YangJae96** [comment]
Thank you!

After task 0 ends, I get error below.

    torch.save(save_dict, "{}_{}.pkl".format(filename, self._cur_task))
  File "/opt/conda/envs/adc/lib/python3.7/site-packages/torch/serialization.py", line 369, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/opt/conda/envs/adc/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/envs/adc/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'weights/lwf/cifar100_lwf_10_10_0.pkl'


Maybe additional code that generated the weights/lwf/  directory would help to avoid error.

**Comment by dipamgoswami** [comment]
Hi,
Thanks for finding the issue. I have added the code to create the directory now.
